spring.application.name=databasepostgre
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=passkord

# command di bawah ini untuk ngasih tahu kalau setiap spring boot run maka semua sql kueri dijalankans
#spring.sql.init.mode=always