spring.datasource.url=jdbc:postgresql://localhost:5432/rumah
spring.datasource.username=roni
spring.datasource.password=Theo@2804
spring.sql.init.mode=always
spring.datasource.initialization-mode=always
spring.datasource.platform=postgres